name: 'Start Lando app'
author: 'Tomasz Pluskiewicz'
description: 'Starts lando services'

inputs:
  healthcheck:
    description: URL to await
    required: false
  timeout:
    description: Time in milliseconds to wait for lando app to start (default 10s)
    required: false
    default: "10000"
  ignore-errors:
    description: Ignore errors and continue
    required: false
    default: "false"

runs:
  using: node20
  main: "dist/index.js"

branding:
  icon: box
  color: purple
