name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.MAZE_LINKER_APP_ID }}
        private_key: ${{ secrets.MAZE_LINKER_PRIVATE_KEY }}
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ steps.generate_token.outputs.token }}
